// Forward version.dll exports to the real system DLL (Discord loads our DLL by name)
// VerLanguageName* lives in KERNEL32 on current Windows builds
#pragma comment(linker, "/export:GetFileVersionInfoA=api-ms-win-core-version-l1-1-0.GetFileVersionInfoA")
#pragma comment(linker, "/export:GetFileVersionInfoByHandle=api-ms-win-core-version-l1-1-0.GetFileVersionInfoByHandle")
#pragma comment(linker, "/export:GetFileVersionInfoExA=api-ms-win-core-version-l1-1-0.GetFileVersionInfoExA")
#pragma comment(linker, "/export:GetFileVersionInfoExW=api-ms-win-core-version-l1-1-0.GetFileVersionInfoExW")
#pragma comment(linker, "/export:GetFileVersionInfoSizeA=api-ms-win-core-version-l1-1-0.GetFileVersionInfoSizeA")
#pragma comment(linker, "/export:GetFileVersionInfoSizeExA=api-ms-win-core-version-l1-1-0.GetFileVersionInfoSizeExA")
#pragma comment(linker, "/export:GetFileVersionInfoSizeExW=api-ms-win-core-version-l1-1-0.GetFileVersionInfoSizeExW")
#pragma comment(linker, "/export:GetFileVersionInfoSizeW=api-ms-win-core-version-l1-1-0.GetFileVersionInfoSizeW")
#pragma comment(linker, "/export:GetFileVersionInfoW=api-ms-win-core-version-l1-1-0.GetFileVersionInfoW")
#pragma comment(linker, "/export:VerFindFileA=api-ms-win-core-version-l1-1-0.VerFindFileA")
#pragma comment(linker, "/export:VerFindFileW=api-ms-win-core-version-l1-1-0.VerFindFileW")
#pragma comment(linker, "/export:VerInstallFileA=api-ms-win-core-version-l1-1-0.VerInstallFileA")
#pragma comment(linker, "/export:VerInstallFileW=api-ms-win-core-version-l1-1-0.VerInstallFileW")
#pragma comment(linker, "/export:VerLanguageNameA=KERNEL32.VerLanguageNameA")
#pragma comment(linker, "/export:VerLanguageNameW=KERNEL32.VerLanguageNameW")
#pragma comment(linker, "/export:VerQueryValueA=api-ms-win-core-version-l1-1-0.VerQueryValueA")
#pragma comment(linker, "/export:VerQueryValueW=api-ms-win-core-version-l1-1-0.VerQueryValueW")
